#!/usr/bin/perl -w

# Tarball name passed as first param
$tarname = $ARGV [0];

# Get top-level source file names
$srcfiles = qx{svn list | grep -v / | sort};
$srcfiles =~ s/\n/ /g;

@subdirs = split (' ', qx{svn list | grep / | sort});
foreach $dir (@subdirs)
{
   @dirlist = split (' ', qx{svn list $dir | sort});
   map { $_ = $dir . $_ } @dirlist;
   $srcfiles = "$srcfiles " . join (" ", @dirlist);
}

system ("tar cvjf $tarname $srcfiles");
